<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-31T11:39:56 EDT" name="Default suite" finished-at="2021-03-31T11:39:59 EDT" duration-ms="3254">
    <groups>
    </groups>
    <test started-at="2021-03-31T11:39:56 EDT" name="Default test" finished-at="2021-03-31T11:39:59 EDT" duration-ms="3254">
      <class name="com.automation.tests.SingleUserTest">
        <test-method is-config="true" signature="loadProperties()[pri:0, instance:com.automation.tests.SingleUserTest@1ddf84b8]" started-at="2021-03-31T11:39:56 EDT" name="loadProperties" finished-at="2021-03-31T11:39:56 EDT" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadProperties -->
        <test-method is-config="true" signature="initializePOJOs()[pri:0, instance:com.automation.tests.SingleUserTest@1ddf84b8]" started-at="2021-03-31T11:39:56 EDT" name="initializePOJOs" finished-at="2021-03-31T11:39:56 EDT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePOJOs -->
        <test-method is-config="true" signature="requestSetup()[pri:0, instance:com.automation.tests.SingleUserTest@1ddf84b8]" started-at="2021-03-31T11:39:56 EDT" name="requestSetup" finished-at="2021-03-31T11:39:58 EDT" duration-ms="1336" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- requestSetup -->
        <test-method is-config="true" signature="setupEndPt()[pri:0, instance:com.automation.tests.SingleUserTest@1ddf84b8]" started-at="2021-03-31T11:39:58 EDT" name="setupEndPt" finished-at="2021-03-31T11:39:58 EDT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupEndPt -->
        <test-method signature="newsingleUserValidation_id2()[pri:0, instance:com.automation.tests.SingleUserTest@1ddf84b8]" started-at="2021-03-31T11:39:58 EDT" name="newsingleUserValidation_id2" finished-at="2021-03-31T11:39:59 EDT" duration-ms="1829" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [200] but found [403]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [200] but found [403]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.automation.tests.SingleUserTest.newsingleUserValidation_id2(SingleUserTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newsingleUserValidation_id2 -->
      </class> <!-- com.automation.tests.SingleUserTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
